# Generated by Django 5.0.8 on 2025-07-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_title'),
    ]

    operations = [
        # First, clear all data to avoid conversion issues
        migrations.RunSQL(
            "DELETE FROM todo_task;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DELETE FROM todo_category;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DELETE FROM todo_contextentry;",
            reverse_sql=""
        ),
        
        # Reset sequences
        migrations.RunSQL(
            "ALTER SEQUENCE IF EXISTS todo_category_id_seq RESTART WITH 1;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "ALTER SEQUENCE IF EXISTS todo_task_id_seq RESTART WITH 1;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "ALTER SEQUENCE IF EXISTS todo_contextentry_id_seq RESTART WITH 1;",
            reverse_sql=""
        ),
        
        # Alter the ID fields to UUID
        migrations.RunSQL(
            "ALTER TABLE todo_category ALTER COLUMN id TYPE uuid USING gen_random_uuid();",
            reverse_sql="ALTER TABLE todo_category ALTER COLUMN id TYPE bigint;"
        ),
        migrations.RunSQL(
            "ALTER TABLE todo_task ALTER COLUMN id TYPE uuid USING gen_random_uuid();",
            reverse_sql="ALTER TABLE todo_task ALTER COLUMN id TYPE bigint;"
        ),
        migrations.RunSQL(
            "ALTER TABLE todo_contextentry ALTER COLUMN id TYPE uuid USING gen_random_uuid();",
            reverse_sql="ALTER TABLE todo_contextentry ALTER COLUMN id TYPE bigint;"
        ),
        
        # Alter the category_id foreign key
        migrations.RunSQL(
            "ALTER TABLE todo_task ALTER COLUMN category_id TYPE uuid USING gen_random_uuid();",
            reverse_sql="ALTER TABLE todo_task ALTER COLUMN category_id TYPE bigint;"
        ),
    ]
