# Generated by Django 5.2.4 on 2025-07-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_ai_confidence_task_ai_enhanced_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ai_confidence',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ai_enhanced_description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ai_processed_at',
        ),
        migrations.DeleteModel(
            name='AIAnalysis',
        ),
    ]
