# Generated by Django 5.2.4 on 2025-07-05 19:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_task_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-usage_frequency', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contextentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Context Entry', 'verbose_name_plural': 'Context Entries'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name (must be unique)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='usage_frequency',
            field=models.IntegerField(default=0, help_text='Number of times this category has been used', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contextentry',
            name='content',
            field=models.TextField(help_text='The actual message, email, or note content'),
        ),
        migrations.AlterField(
            model_name='contextentry',
            name='processed_insights',
            field=models.TextField(blank=True, help_text='AI-processed insights', null=True),
        ),
        migrations.AlterField(
            model_name='contextentry',
            name='source_type',
            field=models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('Note', 'Note')], help_text='Type of source', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Associated category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Task deadline', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Task description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2, help_text='Task priority level', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority_score',
            field=models.FloatField(blank=True, help_text='AI-computed priority score (0.0 to 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', help_text='Current task status', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Task title', max_length=200),
        ),
        migrations.AddIndex(
            model_name='contextentry',
            index=models.Index(fields=['source_type'], name='todo_contex_source__985dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='contextentry',
            index=models.Index(fields=['created_at'], name='todo_contex_created_e9dfc7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='todo_tasks_status_0495c1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='todo_tasks_priorit_8f2f51_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='todo_tasks_deadlin_929e40_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category'], name='todo_tasks_categor_11f81e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='todo_tasks_created_56373c_idx'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='todo_categories',
        ),
        migrations.AlterModelTable(
            name='contextentry',
            table='todo_context_entries',
        ),
        migrations.AlterModelTable(
            name='task',
            table='todo_tasks',
        ),
    ]
